/**
 * @license
 * Copyright 2022 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.POM({
  name: "notification",
  version: 1,
  files: [
    { name: "Notifiable",                                                    flags: "js|java" },
    { name: "ClientResendNotificationService",                               flags: "js|java" },
    { name: "DAONotificationRuleAction",                                     flags: "js|java" },
    { name: "EmailSetting",                                                  flags: "js|java" },
    { name: "GoogleChatSetting",                                             flags: "js|java" },
    { name: "MyNotificationDAO",                                             flags: "js|java" },
    { name: "Notification",                                                  flags: "js|java" },
    { name: "NotificationCitationView",                                      flags: "js" },
    { name: "NotificationExpansionDAO",                                      flags: "js|java" },
    { name: "NotificationGoogleChatRefines",                                 flags: "js|java" },
    { name: "NotificationHostnameRuleAction",                                flags: "js|java" },
    { name: "NotificationMessageModal",                                      flags: "js" },
    { name: "NotificationSlackRefines",                                      flags: "js|java" },
    { name: "NotificationTemplateDAO",                                       flags: "js|java" },
    { name: "NotificationView",                                              flags: "js" },
    { name: "NotificationRowView",                                           flags: "js" },
    { name: "NotificationSetting",                                           flags: "js|java" },
    { name: "NotificationSettingsView",                                      flags: "js" },
    { name: "NotificationNotificationView",                                  flags: "js" },
    { name: "ResendNotificationServiceInterface",                            flags: "js|java" },
    { name: "ScriptRunNotification",                                         flags: "js" },
    { name: "ScriptRunNotificationNotificationCitationView",                 flags: "js" },
    { name: "SlackSetting",                                                  flags: "js|java" },
    { name: "ToastNotificationDAO",                                          flags: "js|java" },
    { name: "ToastState",                                                    flags: "js|java" },
    { name: "email/EmailConfig",                                             flags: "js|java" },
    { name: "email/EmailFolderAgent",                                        flags: "java" },
    { name: "email/EmailMessage",                                            flags: "js|java" },
    { name: "email/EmailMessagePropertyServiceRuleAction",                   flags: "js|java" },
    { name: "email/EmailMessageStatusRuleAction",                            flags: "js|java" },
    { name: "email/EmailServiceConfig",                                      flags: "js|java" },
    { name: "email/EmailTemplate",                                           flags: "js|java" },
    { name: "email/EmailTemplateSource",                                     flags: "js|java" },
    { name: "email/SMTPAgent",                                               flags: "js|java" },
    { name: "email/SMTPConfig",                                               flags: "js|java" },
    { name: "email/Status",                                                  flags: "js|java" },
    { name: "email/test/EmailMessageRuleTest",                               flags: "js|java" },
    { name: "email/test/MockSMTPAgent",                                      flags: "js|java" },
    { name: "email/test/MockSMTPAgentTest",                                  flags: "js|java" },
    { name: "email/EmailPropertyService",                                    flags: "js|java" },
    { name: "email/EmailTemplateEngine",                                     flags: "js|java" },
    { name: "email/ChainedPropertyService",                                  flags: "js|java" },
    { name: "email/EmailTemplateApplyEmailPropertyService",                  flags: "js|java" },
    { name: "email/GroupEmailTemplateService",                               flags: "js|java" },
    { name: "email/EmailConfigEmailPropertyService",                         flags: "js|java" },
    { name: "email/EmailMessageValidationPropertyService",                   flags: "js|java" },
    { name: "email/ApplyBaseArgumentsEmailPropertyService",                  flags: "js|java" },
    { name: "sms/NullSMSService",                                            flags: "js|java" },
    { name: "sms/ProxySMSService",                                           flags: "js|java" },
    { name: "push/PushService",                                              flags: "js|java" },
    { name: "push/FirebasePushService",                                      flags: "js|java" },
    { name: "sms/SMSMessage",                                                flags: "js|java" },
    { name: "sms/SMSService",                                                flags: "js|java" },
    { name: "sms/SMSSetting",                                                flags: "js|java" },
    { name: "sms/SMSStatus",                                                 flags: "js|java" },
    { name: "sms/TwilioConfig",                                              flags: "js|java" },
    { name: "sms/TwilioSMSService",                                          flags: "js|java" },
    { name: "test/DAONotificationTest",                                      flags: "js|java" },
    { name: "email/ClientPOP3EmailService",                                  flags: "js|java" },
    { name: "email/POP3Email",                                               flags: "js|java" },
    { name: "broadcast/BroadcastNotification",                               flags: "js|java" },
    { name: "broadcast/SendNotificationView",                                flags: "web" },
    { name: "broadcast/BroadcastNotificationFacade",                         flags: "web" },
    { name: "broadcast/BroadcastNotificationNotificationCitationView",       flags: "web" },
  ]
});
